version: '3.8'

services:
  # PostgreSQL for Auth Service
  auth-db:
    image: postgres:15-alpine
    container_name: smart-learning-auth-db
    environment:
      POSTGRES_DB: auth_service_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL for User Service
  user-db:
    image: postgres:15-alpine
    container_name: smart-learning-user-db
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_password
    ports:
      - "5433:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_service -d user_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: smart-learning-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smart-learning-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@smartlearning.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - auth-db
      - user-db

volumes:
  auth_db_data:
  user_db_data:
  redis_data:
  pgadmin_data:

networks:
  default:
    name: smart-learning-network

